GSoC Week 2 PR: Created the wrapper class with basic functionality
3V3RYONE/metasploit-framework pull request #1
Opened 2022-06-21 12:24 UTC by 3V3RYONE

Created a initial wrapper class for HTTP-Trace. Verified that the initialization message is shown when an object of the wrapper class is created.  (Task 1 of Week 2)

2022-06-22 12:14 UTC, 3V3RYONE commented
Established and verified the connection betn wrapper class and client and server. This completes Task 1 of Week 2.  
  
Output showing the two methods of wrapper class being called when HTTP-Tracing is put to action.  
  
![output_week2_task1](https://drive.google.com/uc?export=view&id=1qq0LGJzZmGOdTD1tcvhfh1hm2cm8Jr99)

2022-06-23 17:00 UTC, gwillcox-r7 requested changes
Missing logging responses from the server. Also would have liked to have seen some initial attempts to display the data vs just displaying static messages. Doesn't have to be perfect but shows at least your looking into how to render the data.

2022-06-23 17:00 UTC, gwillcox-r7 commented on lib/rex/proto/http/server.rb
> +
This is only logging responses, what about requests that come in to the HTTP server? Those are also important to log and show to the end user.

2022-06-25 13:22 UTC, 3V3RYONE commented
With the new commits, I allowed logging of requests at server side. Also, the definition of methods and constructor of the class have been improved, i.e. now they accept the datastore options for HTTP-Trace, and if the option is set, the tracing is enabled.  
  
![updated_output](https://drive.google.com/uc?export=view&id=1Lo14hM74n2H1v19sAskuz-OQLP3A1R5x)  
  
This implements all 3 Tasks of Week 2.

2022-06-27 13:34 UTC, gwillcox-r7 approved these changes
LGTM, go for it :)

2022-06-27 13:37 UTC, merged