Add procs required for logging HTTP requests and responses in Login Scanners
3V3RYONE/metasploit-framework pull request #4
Opened 2022-07-29 13:15 UTC by 3V3RYONE

*pass*

2022-07-29 13:34 UTC, gwillcox-r7 approved these changes

2022-08-01 15:17 UTC, gwillcox-r7 commented on lib/metasploit/framework/login_scanner/http.rb
> +                (http_trace_colors || '').split('/').map { |color| "%bld%#{color}" }
Should probably be "%red/%blu" here as a default

2022-08-01 15:20 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +          (datastore['HttpTraceColors'] || '').split('/').map { |color| "%bld%#{color}" }
Should probably be "%red/%blu" here as a default

2022-08-01 15:21 UTC, gwillcox-r7 requested changes
Just need to update these defaults and should be good to go

2022-08-01 17:27 UTC, gwillcox-r7 approved these changes

2022-08-01 17:34 UTC, 3V3RYONE commented
Verification steps:
1. Open msfconsole
2. Use a login scanner that accesses **Metasploit::Framework::LoginScanner::HTTP**. (e.g. `auxiliary/scanner/http/symantec_web_gateway`)
3. Set the target, set HttpTrace to true.
4. **Verify** that requests and responses are being logged to console.
5. Similarly, set the other datastore option HttpTraceHeadersOnly to true.
6. **Verify** that only the headers of requests and responses only are being logged to console.
7. Set HttpTraceColors to any pair of color like 'blu/grn'.
8. **Verify** that requests and responses are being logged in those colors.

9. Use a login scanner that accesses **Msf::Core::Exploit::Remote::HttpClient**. ( e.g. `auxiliary/scanner/http/title`)
10. Repeat steps 3 to 8 for this login scanner as well.

2022-08-01 17:48 UTC, gwillcox-r7 commented
Before:
```
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > show options

Module options (auxiliary/scanner/http/symantec_web_gateway_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DB_SKIP_EXISTING  none             no        Skip existing credentials stored in the current database (Accepted: none, user,
                                                user&realm)
   PASSWORD                           no        The password to specify for authentication
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                             yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Usin
                                                g-Metasploit
   RPORT             443              yes       The target port (TCP)
   SSL               true             no        Negotiate SSL/TLS for outgoing connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads (max one per host)
   USERNAME                           no        The username to specify for authentication
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/symantec_web_gateway_login) > set RHOST www.google.com
RHOST => www.google.com
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > set HttpTrace true
HttpTrace => true
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > run

[-] 142.250.68.132:443 - Target is not Symantec Web Gateway
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/symantec_web_gateway_login) >
```

After:

```
 ~/git/metasploit-framework │ add-datastore-callback ?32  ./msfconsole                                      ✔ │ 10s │ 3.0.2 Ruby 
                                                  
                          ########                  #
                      #################            #
                   ######################         #
                  #########################      #
                ############################
               ##############################
               ###############################
              ###############################
              ##############################
                              #    ########   #
                 ##        ###        ####   ##
                                      ###   ###
                                    ####   ###
               ####          ##########   ####
               #######################   ####
                 ####################   ####
                  ##################  ####
                    ############      ##
                       ########        ###
                      #########        #####
                    ############      ######
                   ########      #########
                     #####       ########
                       ###       #########
                      ######    ############
                     #######################
                     #   #   ###  #   #   ##
                     ########################
                      ##     ##   ##     ##
                            https://metasploit.com


       =[ metasploit v6.2.4-dev-01423aeb04                ]
+ -- --=[ 2228 exploits - 1172 auxiliary - 398 post       ]
+ -- --=[ 867 payloads - 45 encoders - 11 nops            ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: You can pivot connections over sessions 
started with the ssh_login modules

msf6 payload(windows/x64/meterpreter/reverse_tcp) > use auxiliary/scanner/http/symantec_web_gateway_login
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > show options

Module options (auxiliary/scanner/http/symantec_web_gateway_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DB_SKIP_EXISTING  none             no        Skip existing credentials stored in the current database (Accepted: none, user,
                                                user&realm)
   PASSWORD                           no        The password to specify for authentication
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                             yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Usin
                                                g-Metasploit
   RPORT             443              yes       The target port (TCP)
   SSL               true             no        Negotiate SSL/TLS for outgoing connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads (max one per host)
   USERNAME                           no        The username to specify for authentication
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/symantec_web_gateway_login) > set HttpTrace true
HttpTrace => true
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > set RHOST www.google.com
RHOST => www.google.com
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > run
####################
# Request:
####################
GET /spywall/login.php HTTP/1.1
Host: www.google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36


####################
# Response:
####################
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1578
Date: Mon, 01 Aug 2022 17:45:35 GMT
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q0 [...]

2022-08-01 17:49 UTC, gwillcox-r7 commented
![image](https://user-images.githubusercontent.com/63261883/182210771-48232085-e49b-46f7-9195-3ed33be68762.png)

Showing the colors work for default colors.

2022-08-01 17:54 UTC, gwillcox-r7 commented
```
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > set HttpTraceHeadersOnly true
HttpTraceHeadersOnly => true
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > run
####################
# Request:
####################
GET /spywall/login.php HTTP/1.1
Host: www.google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36

####################
# Response:
####################
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1578
Date: Mon, 01 Aug 2022 17:53:41 GMT
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"



[-] 142.250.115.147:443 - Target is not Symantec Web Gateway
[*] Scanned  1 of 10 hosts (10% complete)
*cut for brevity*
msf6 auxiliary(scanner/http/symantec_web_gateway_login) > 
```

Seems the shortened header only option is working fine :)

2022-08-01 17:57 UTC, gwillcox-r7 commented
Different colors for highlights in requests and responses working well: 

![image](https://user-images.githubusercontent.com/63261883/182212002-84a45f7c-721a-45e8-b1d7-92f97b00121a.png)

2022-08-01 18:03 UTC, 3V3RYONE commented
Awesome, should be good to land now then :)

2022-08-01 18:06 UTC, gwillcox-r7 commented
Other side of things with the Msf::Core::Exploit::Remote::HttpClient library, showing that that is working:

```
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use auxiliary/scanner/http/title
msf6 auxiliary(scanner/http/title) > set RHOST www.google.com
RHOST => www.google.com
msf6 auxiliary(scanner/http/title) > set HttpTrace true
HttpTrace => true
msf6 auxiliary(scanner/http/title) > run

####################
# Request:
####################
GET / HTTP/1.1
Host: www.google.com
User-Agent: Mozilla/5.0 (iPad; CPU OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1


####################
# Response:
####################
HTTP/1.1 302 Found
Location: https://www.google.com/?gws_rd=ssl
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Date: Mon, 01 Aug 2022 18:03:24 GMT
Server: gws
Content-Length: 231
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: 1P_JAR=2022-08-01-18; expires=Wed, 31-Aug-2022 18:03:24 GMT; path=/; domain=.google.com; Secure; SameSite=none, AEC=AakniGPgRnYxEY4J7xvXhrz2N8XSG8fDBWDRJcvTMXgtFiDtc0DkZmvYPMY; expires=Sat, 28-Jan-2023 18:03:24 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="gfe-default_product_name"
Report-To: {"group":"gfe-default_product_name","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/default_product_name"}]}

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/?gws_rd=ssl">here</A>.
</BODY></HTML>

[+] [142.251.45.36:80] [C:302] [R:https://www.google.com/?gws_rd=ssl] [S:gws] 302 Moved
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/title) > set HttpTraceHeadersOnly true
HttpTraceHeadersOnly => true
msf6 auxiliary(scanner/http/title) > run

####################
# Request:
####################
GET / HTTP/1.1
Host: www.google.com
User-Agent: Mozilla/5.0 (iPad; CPU OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1

####################
# Response:
####################
HTTP/1.1 302 Found
Location: https://www.google.com/?gws_rd=ssl
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Date: Mon, 01 Aug 2022 18:03:33 GMT
Server: gws
Content-Length: 231
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: 1P_JAR=2022-08-01-18; expires=Wed, 31-Aug-2022 18:03:33 GMT; path=/; domain=.google.com; Secure; SameSite=none, AEC=AakniGN1FM7gbUsVZWSyV4jOqe2bc5Ew1jvkOGel4QBbDl5evAk841y8jRk; expires=Sat, 28-Jan-2023 18:03:33 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="gfe-default_product_name"
Report-To: {"group":"gfe-default_product_name","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/default_product_name"}]}


[+] [142.251.45.36:80] [C:302] [R:https://www.google.com/?gws_rd=ssl] [S:gws] 302 Moved
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/title) >
```

And here is the colors, also working:

![image](https://user-images.githubusercontent.com/63261883/182213312-666e5ff8-fe38-4f60-a7ad-efddc242266c.png)

2022-08-01 18:06 UTC, gwillcox-r7 commented
LGTM, feel free to land this 👍

2022-08-03 13:38 UTC, gwillcox-r7 approved these changes

2022-08-04 16:36 UTC, merged